### ISSUE TITLE
Remove installation of `python3-setuptools` when possible

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ansible-role-pip#60]
# 💡 Summary #

Revert addition of `python3-setuptools` in `vars/Debian.yml` when that becomes possible.

## Motivation and context ##

In #61 we added some code to explicitly install `python3-setuptools` because that package is not currently getting installed on Kali, which is based on Debian Testing.  Once this situation is resolved in Debian Testing this change can be reverted.

**Comment by mcdonnnj** [comment]
This appears to have been done intentionally in the upstream Debian Testing (currently Trixie). Per the [changelog for the `python3-pip` package](https://metadata.ftp-master.debian.org/changelogs//main/p/python-pip/python-pip_24.0+dfsg-2_changelog) (emphasis mine):
> python-pip (24.0+dfsg-2) unstable; urgency=medium
>
>   * **Drop Depends on python3-distutils and python3-setuptools, no longer
>   necessary when doing isolated builds.**
>   * Build manpages from pip's Sphinx documentation. This builds a fleet of
>     manpages, instead of one, but it's at least up to date. (Closes: #1061184)
>
>  -- Stefano Rivera <stefanor@debian.org>  Tue, 05 Mar 2024 23:29:00 -0400

**Comment by jsf9k** [comment]
Well I guess the changes from #61 should be permanent then.

**Comment by jsf9k** [comment]
I will close this issue, as the changes made in #61 _should not_ be reverted.
